USB_VID = 0x303A
USB_PID = 0x7099
USB_PRODUCT = "Waveshare-ESP32-P4-WIFI6"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32p4

CIRCUITPY_ESP_FLASH_SIZE = 32MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_SIZE = 32MB
CIRCUITPY_ESP_PSRAM_MODE = hpi
CIRCUITPY_ESP_PSRAM_FREQ = 200m
